HADOOP_USER_PASSWORD=hadoop
HADOOP_VERSION=3.3.1
HADOOP_ORIGIN=https://dlcdn.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
HADOOP_PARENT_DIR=/usr/local

HDFS_DATANODE_USER=root
HDFS_SECONDARYNAMENODE_USER=root
YARN_RESOURCEMANAGER_USER=root
YARN_NODEMANAGER_USER=root
